const CONST = { 
    EV_MOUNT_COMPONENT: 'EV_MOUNT_COMPONENT',
    EV_CHANGE_NAVIGATE: 'EV_CHANGE_NAVIGATE',
    EV_CHANGE_CONTENT:  'EV_CHANGE_CONTENT',
    EV_CHANGE_ROOM:     'EV_CHANGE_ROOM',
    EV_SYNC_DATA:       'EV_SYNC_DATA',
    EV_PUSH_LIST:       'EV_PUSH_LIST',
    EV_REMOVE_LIST:     'EV_REMOVE_LIST',

    EV_CALL_API:        'EV_CALL_API',
    EV_CALL_API_SUCCESS:'EV_CALL_API_SUCCESS',
    EV_CALL_API_ERROR:  'EV_CALL_API_ERROR',
    EV_CHANGE_ROOM:     'EV_CHANGE_ROOM',
    EV_GO_TO_POSITION:  'EV_GO_TO_POSITION',
    EV_GO_TO_MESSAGE_ID:'EV_GO_TO_MESSAGE_ID',
    EV_GO_TO_BOTTOM:    'EV_GO_TO_BOTTOM',
    EV_SCROLL_NOT_READ: 'EV_SCROLL_NOT_READ',
    EV_EDIT_MESSAGE:    'EV_EDIT_MESSAGE',
    EV_SEND_MESSAGE:    'EV_SEND_MESSAGE',
    EV_APPEND_CONTENT:  'EV_APPEND_CONTENT',
    EV_SHOW_IMAGE:      'EV_SHOW_IMAGE',
}

export default CONST;
 